language: cpp
os:
  - linux
  - osx
dist: bionic
osx_image: xcode7.3

env:
  matrix:
    - CONFIGURATION="Debug"
    - CONFIGURATION="Release"

# Install dependencies for Linux builds. libc6-i386 is needed to run the 32-bit premake4 binary.
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update && sudo apt-get install libc6-i386 libgtk-3-dev; fi

# Build and install wxWidgets, with our custom tweaks patch
install:
  - ./build-wxwidgets.sh $CONFIGURATION

# Cache the compiled wxWidgets so it can be in with future builds
cache:
  directories:
    - $HOME/wxWidgets-3.1.0

# Run premake to create the Xcode project
before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./premake5 --wx-config-debug=$HOME/wxWidgets-$WX_VERSION/bin/wx-config --wx-config-release=$HOME/wxWidgets-$WX_VERSION/bin/wx-config xcode4; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./premake5-linux --wx-config-debug=$HOME/wxWidgets-$WX_VERSION/bin/wx-config --wx-config-release=$HOME/wxWidgets-$WX_VERSION/bin/wx-config gmake; fi

# Build XWord
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then xcodebuild -project build/xcode4/XWord.xcodeproj -configuration "$CONFIGURATION Native" build; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make -C build/gmake config=${CONFIGURATION,,}; fi

# For deployed Mac builds, zip the .app folder
before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pushd bin/$CONFIGURATION && zip -r XWord-macOS.zip XWord.app/ -x *.fbp && popd; fi

# Deploy tagged release builds to GitHub Releases
# TODO(#40): Deployment for Linux.
deploy:
  provider: releases
  api_key:
    secure: dT5W1MsTMFYjN6mDnSqpL7QjHkL/R6When5elNX9dwGLafCyRN2ohAUa6lpt17v8NG3//qF9BZLZOymA7D9kNqILGbt8mjCu053WBknekI9BTG593HQhsV2y0nA8p2J3y95/Qdty/t0jg/QdWqV60O0w6VQFGoHOb9EUVKCu9cR+WX4kVz2uadB8ms8r2YDeC0fUnrA/w1XnopohJw3P/hiV6S2+u1eeWFFyjOTuTJcyg6cHkxMysj/4N4llxOU/to0/nQYKg+sc9B7hHLFmwHxLbq1prn9LG9kRwDmCnzNlV0OgPOT2vP+LSwyfvp4zuHNC61sIH8OSVKCmn3keM/ZDahKB37Zd0eQKBxLNm9iu/UibBN7R+4QtVXgPkfqZb9bFhpy9fi+MxiYXUzbl3q3p7werLooI42KFzkJ2KxSkP3ZEQko3XsdAdgeBZVXzD/Ze0IMnaTQSeCPQbzbMjXA0mIwOkWCIj77dqOnQOdjAURA+U5tUt1Q2TUa9yJHXT5O6J2XNXdCbM5JlzBNoo9orcTjuwnsyplvMovKw1Qx0DGVG0hNakp2tNszsH4LeJKrAdWr1KXGu392Shq3XCya3X76jhQBO9zMDAe0txdFpnmx6Pi8GYlFabU2OWoWmNsnJVxOsMGKL8wz1vRx4uakFY4WzgDO/SI/6zkQ43W8=
  file: bin/$CONFIGURATION/XWord-macOS.zip
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = "osx" && $CONFIGURATION = "Release"
