language: cpp
os:
  - linux
  - osx
dist: bionic
osx_image: xcode7.3

env:
  global:
    - WX_VERSION="3.1.3"
  matrix:
    - CONFIGURATION="Debug"
    - CONFIGURATION="Release"

# Install dependencies for Linux builds
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update && sudo apt-get install libgtk-3-dev; fi

# Build and install wxWidgets, with our custom tweaks patch
install:
  - ./build-wxwidgets.sh $WX_VERSION $CONFIGURATION

# Cache the compiled wxWidgets so it can be in with future builds
cache:
  directories:
    - $HOME/wxWidgets-$WX_VERSION

# Run premake to create the Xcode project
before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./premake5 --wx-config-debug=$HOME/wxWidgets-$WX_VERSION/bin/wx-config --wx-config-release=$HOME/wxWidgets-$WX_VERSION/bin/wx-config xcode4; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./premake5-linux --wx-config-debug=$HOME/wxWidgets-$WX_VERSION/bin/wx-config --wx-config-release=$HOME/wxWidgets-$WX_VERSION/bin/wx-config gmake; fi

# Build XWord
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then xcodebuild -project build/xcode4/XWord.xcodeproj -configuration "$CONFIGURATION" build; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make -C build/gmake config=${CONFIGURATION,,}; fi

# For deployed Mac builds, zip the .app folder
before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pushd bin/$CONFIGURATION && zip -r XWord-macOS.zip XWord.app/ -x *.fbp -x "*/scripts/_*" -x "*/scripts/*debug*" && popd; fi

# Deploy tagged release builds to GitHub Releases
# TODO(#40): Deployment for Linux.
deploy:
  provider: releases
  api_key:
    secure: SAIRYZABLK3ZLwBdtAkQ5U3UiOCL9TyH4ryfSkaz/Y2VnFcOX/sUJFvXHWnOVLQ8rIoSzINUSPz4++QxOzt3Dl0Ae0THwNYHr58zu9t242KISGYa9DE3yR9ef7bkTj29xuPZTnvAAEirxBbaJNeI//jXfiwJsmzRDVvL7/VlL49OOsmZhW/berMbsF9fo/wcmlDaL1v6e2ak0jph78F4P4z75H08SdJis4Ymg7a6nC8xmONeaf2zFauLHGAhTuDZiavj0jfdOlg4ePA0uAHAz7Y9gIy2NHQV9pt8kLwehvK0o8k2YTRECX9LCg+S3G5YPBC2Q8Flpc8drPbxJcZbGL7Rr991zLExUVGuRFGFSGxbJ3J0VfEBZ3J5CqPL80j3bZTLoKzg3UyGfYGbZBbzBue2h4qXzzVuzyFXBSvr1QF0mLE+pGt+2qQgFsg4AEwSkSha86z6kILHz7PE+PxKHJchpCwDP4yPKSFa9V5bENxpPd50cggRNYB0nolQQoUAOYFEAlbJ+cqS85QTXzP8Wb8e1VrSc8VXKrkG+G0jJzEo9/+2RCPLaSx4obzrQ/ZhzmNJ+RUHpW0oFJgaKosBIYXQOmlu2yv4sJmsKHHod2tC9e8SWAAtwKdyxUYFOfdFroxh/fmiPkLs118NhN6r31nEYilUimpjPmqmNJKZJCg=
  file: bin/$CONFIGURATION/XWord-macOS.zip
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = "osx" && $CONFIGURATION = "Release"
