version: '{build}'
test: off

configuration:
  - Debug
  - Release

environment:
  WX_VERSION: 3.1.2

# Build and install wxWidgets, with our custom tweaks patch
install:
  - call "%ProgramFiles(x86)%\Microsoft Visual Studio 10.0\VC\vcvarsall.bat"
  - bash build-wxwidgets.sh %WX_VERSION% %CONFIGURATION%

# Cache the compiled wxWidgets so it can be in with future builds
cache:

# Run premake4 to create the Visual Studio project
before_build:
  - premake4.exe --platform=x32 --wx-prefix="%USERPROFILE%/wxWidgets-%WX_VERSION%" vs2010

# Build XWord
build_script:
  - msbuild build/vs2010/XWord.sln /p:Configuration=%CONFIGURATION%

# For deployed builds, zip the build folder
after_build:
  - 7z a bin\%CONFIGURATION%\XWord-Windows.zip "%APPVEYOR_BUILD_FOLDER%\bin\%CONFIGURATION%\*" -r -x!*.exp -x!*.lib -x!*.pdb -x!*.idb -x!*.ilk -x!*.fbp

artifacts:
  path: bin\%CONFIGURATION%\XWord-Windows.zip
  name: XWord-Windows.zip

# Deploy tagged release builds to GitHub Releases
deploy:
  provider: GitHub
  auth_token:
    secure: 0AD8nO40h9vWf+OPhM0O+yCzi6qcnIfqIyfujtkjTEdFHMW5TB2WXZTAKzDHd2UI
  artifact: XWord-Windows.zip
  on:
    appveyor_repo_tag: true
    configuration: Release
